### ISSUE TITLE
Putting this theme in themes.getnikola.com

### ISSUE THREAD

**Issue by ralsina** [Cadair/cadair-nikola-theme#3]
Hi there!

Would you mind if I did some github trickery to put your theme at themes.getnikola.com?

Full attribution of course (and anything you want to say via README.md is displayed)

Thanks in advance!

**Comment by Cadair** [comment]
yes, that would be great :)

**Comment by ralsina** [comment]
Doing it, should appear in the theme site today. Thanks!

**Comment by ralsina** [comment]
I added it but it looks strange, probably it's just that the banner image is not in the theme?

**Comment by Cadair** [comment]
hmmm, the image is supposed to be this one: https://github.com/Cadair/cadair-nikola-theme/blob/master/assets/img/home_banner.jpg

It is possible it is misconfigured, as I use a different image on my site.

**Comment by ralsina** [comment]
Ok, I'll take a look and do a PR if something needs changing

**Comment by Cadair** [comment]
Thanks! Sorry I don't really have time to do it myself at the moment. There are a few other things I would like to update as well. I assume I can make a PR to the themes repo to update the submodule later on?

**Comment by ralsina** [comment]
Well, it's a submodule so I guess if you update something I can pull it from here. Not much of a git maven myself :-)

**Comment by Cadair** [comment]
@ralsina I think all the git repo with the submodule in does is store a commit hash, so that would need updating to reflect updates.
